AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%r': '{}'
    '%w': '()'
Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma
