inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/**/*'

Layout/DotPosition:
  EnforcedStyle: trailing
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/Documentation:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%r': '{}'
    '%w': '()'
Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma
Style/WhileUntilDo:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
