sudo: false
language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - jruby-9.2.5.0
before_install: # Fix jruby
  - gem update --system
  - gem install bundler
  - gem update bundler
script: "bundle exec rake spec"
